# Site settings
title: Chip Shop
email: info@gregariousmammal.com
description: > # this means to ignore newlines until "baseurl:"
  Build your Silicon Empire.
#baseurl: ".." # the subpath of your site, e.g. /blog/
# url: "http://chipshopgame.com" # the base hostname & protocol for your site
twitter_username: chrischinch
github_username:  chrischinchilla
permalink: none
comments: true

collections:
  cards:
    output: true
  # manual:
  #   output: true
  #   layout: manual
  concepts:
    output: true
    layout: concept

defaults:
  -
    scope:
      type: cards
    values:
      layout: card
      region: USA
      era: 80s
      approved: N
      image: test.png

picture:
  source: /assets/images/cards
  output: generated
  markup: picture
  presets:
    default:
      # ppi: [1, 1.5]
      attr:
        class: default-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    mediumscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 200
        # height: 200
      source_default:
        width: 200
    listings:
      ppi: [1, 1.5, 2]
      attr:
        class: listings
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        height: 45
      source_default:
        height: 45

# Build settings
markdown: redcarpet

# gems: [ 'jekyll-pandoc-multiple-formats' ]
#
# pandoc:
#   skip: false
#   impose: false
#   output: ./tmp
#   flags: '--template ./_layouts/cards.latex'
#   site_flags:
#   outputs:
#     pdf: '--latex-engine=pdflatex'
