# Site settings
title: Chip Shop
email: info@gregariousmammal.com
description: > # this means to ignore newlines until "baseurl:"
  Build your Silicon Empire.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://chipshopgame.com" # the base hostname & protocol for your site
twitter_username: chrischinch
github_username:  chrischinchilla

collections:
  cards:
    output: true
    # TODO: How to get this to work?
    layout: card
  manual:
    output: true
    # TODO: How to get this to work?
    layout: manual
  concepts:
    output: true
    # TODO: How to get this to work?
    layout: concept

# Build settings
markdown: kramdown
