# Site settings
title: Chip Shop
email: info@gregariousmammal.com
description: > # this means to ignore newlines until "baseurl:"
  Build your Silicon Empire
#baseurl: ".." # the subpath of your site, e.g. /blog/
# url: "http://chipshopgame.com" # the base hostname & protocol for your site
twitter_username: chrischinch
github_username:  chrischinchilla
permalink: none
comments: false
exclude: [pod, build.sh, rebuild.sh, deploy.sh, contribute.md]

collections:
  cards:
    output: true
    layout: card
  # manual:
  #   output: true
  #   layout: manual
  concepts:
    output: true
    layout: concept

defaults:
  -
    scope:
      path: ""
    values:
      layout: "card"
  -
    scope:
      path: ""
      type: "cards"
    values:
      layout: "card"
      region: USA
      era: 80s
      approved: N
      image: test.png
    scope:
      path: ""
      type: "income"
    values:
      layout: card
      region: USA
      era: 80s
      approved: N
      image: test.png
#
# defaults:
#   -
#     scope:
#       path: cards
#       type: cards
#     values:
#       layout: card
#       region: USA
#       era: 80s
#       approved: N
#       image: test.png
#     scope:
#       type: income
#     values:
#       layout: card
#       region: USA
#       era: 80s
#       approved: N
#       image: test.png

picture:
  source: /assets/images
  output: generated
  markup: picture
  presets:
    default:
      # ppi: [1, 1.5]
      attr:
        class: default-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    mediumscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 600
        # height: 200
      source_default:
        width: 600
    listings:
      ppi: [1, 1.5, 2]
      attr:
        class: listings
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        height: 90
      source_default:
        height: 90

# Build settings
markdown: redcarpet
