title: Product Genius
realtitle: Product Genius
cardtype: staff
hardwaretype: null
stafftype: genius
image: img-placeholder.png
imageattribution: Name of person or company
imagelicense: License type
imagelink: Where did this image come from?
legal: null
approved: 'Y'
cost: 2
provides:
  - quality
affects:
  oneoff:
    rand: 1
  ongoing: Reduce the cost of cards in development by 2
description: A product genius helps make a product that little bit better, increasing quality and loyalty.
